# Generated by Django 3.0.3 on 2020-04-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
