# Generated by Django 3.0.3 on 2020-04-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0002_doctor_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('subject', models.CharField(default='', max_length=70)),
                ('msg', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
